{{- with .Values.backend -}}
{{- if .enabled -}}
---
apiVersion: v1
kind: Deployment
metadata:
  name: ewidencja-backend
spec:
  replicas: {{ default 1 .replicas }}
  labels:
    app: ewidencja-backend
    selector:
      matchLabels:
        name: ewidencja-backend
  template:
    metadata:
      labels:
        name: ewidencja-backend
    spec:
      containers:
        - name: ewidencja-backend
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: 3000
          livelinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
{{- if .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ewidencja-backend
spec:
  ports:
    - port: {{ default 3000 .port }}
      targetPort: {{ default 3000 .targetPort }}
      protocol: TCP
  selector:
    name: ewidencja-backend
{{- end }}
---
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ewidencja-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .ingress.host }}
    http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: ewidencja-backend
          port:
            number: {{ default 3000 .port }}
{{ end -}}
---
{{- end -}}
{{- end -}}
