{{- with .Values.frontend -}}
{{- if .enabled -}}
---
apiVersion: v1
kind: Deployment
metadata:
  name: ewidencja-frontend

spec:
  replicas: {{ default 1 .replicas }}
  labels:
    app: ewidencja-frontend
    selector:
      matchLabels:
        name: ewidencja-frontend
  template:
    metadata:
      labels:
        name: ewidencja-frontend
    spec:
      containers:
        - name: ewidencja-frontend

{{- end -}}
{{- end -}}
