{{- with .Values.frontend -}}
{{- if .enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewidencja-frontend
  labels:
    app: ewidencja-frontend
    group: ewidencja
spec:
  replicas: {{ default 1 .replicas }}
  selector:
    matchLabels:
      app: ewidencja-frontend
  template:
    metadata:
      labels:
        app: ewidencja-frontend
        group: ewidencja
    spec:
      containers:
        - name: ewidencja-frontend
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ default "Always" .image.pullPolicy }}
          ports:
            - containerPort: 80
          livelinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          env:
            - name: API_URL
              value: {{ default $.Values.backend.ingress.host .apiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: ewidencja-frontend
spec:
  ports:
    - port: {{ default 80 .port }}
      targetPort: {{ default 80 .targetPort }}
      protocol: TCP
  selector:
    app: ewidencja-frontend
---
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ewidencja-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ewidencja-frontend
            port:
              number: {{ default 80 .port }}
  {{ if $.Values.certificate.enabled -}}
  tls:
  - hosts:
    - {{ .ingress.host }}
    secretName: {{ default "ewidencja-czasu-pracy-certificate-secret" $.Values.certificate.secretName }}
  {{ end }}
{{ end -}}
---
{{- end -}}
{{- end -}}
