{{- with .Values.frontend -}}
{{- if .enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewidencja-frontend
spec:
  replicas: {{ default 1 .replicas }}
  labels:
    app: ewidencja-frontend
    selector:
      matchLabels:
        name: ewidencja-frontend
  template:
    metadata:
      labels:
        name: ewidencja-frontend
    spec:
      containers:
        - name: ewidencja-frontend
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: 80
          livelinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          env:
            - name: API_URL
              value: {{ default $.Values.backend.ingress.host .apiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: ewidencja-frontend
spec:
  ports:
    - port: {{ default 80 .port }}
      targetPort: {{ default 80 .targetPort }}
      protocol: TCP
  selector:
    name: ewidencja-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ewidencja-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .ingress.host }}
    http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: ewidencja-backend
          port:
            number: {{ default 80 .port }}
  {{- if $.Values.certificate.enabled -}}
  tls:
  - hosts:
    - {{ .ingress.host }}
    secretName: {{ default "ewidencja-czasu-pracy-certificate-secret" $.Values.certificate.secretName }}
  {{ end }}
{{- end -}}
{{- end -}}
