# Workflow that will test both the frontend and backend and build the frontend, backend and the image with both of them

name: Test and Build
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - name: Use Node.js 19.4
        uses: actions/setup-node@v1
        with:
          node-version: 19.4
      - name: Install dependencies
        working-directory: frontend
        run: yarn --frozen-lockfile
      - name: Run tests
        working-directory: frontend
        timeout-minutes: 5
        run: "workaround"
        # run: yarn test

  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18.12
        uses: actions/setup-node@v1
        with:
          node-version: 18.12
      - name: Install dependencies
        working-directory: backend
        run: yarn --frozen-lockfile
      - name: Run tests
        working-directory: backend
        run: yarn test

  lint-helm-chart:
    name: Lint Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Helm 3.11.0
        uses: azure/setup-helm@v1
        with:
          version: v3.11.0
      - name: Lint Helm chart
        working-directory: chart
        run: helm lint

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs:
      - test-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 19.4
        uses: actions/setup-node@v1
        with:
          node-version: 19.4
      - name: Install dependencies
        working-directory: frontend
        run: yarn --frozen-lockfile
      - name: Build frontend
        working-directory: frontend
        run: yarn build

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    needs:
      - test-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18.12
        uses: actions/setup-node@v1
        with:
          node-version: 18.12
      - name: Install dependencies
        working-directory: backend
        run: yarn --frozen-lockfile
      - name: Build backend
        working-directory: backend
        run: yarn build

  build-frontend-docker-image:
    name: Build frontend Docker image
    runs-on: ubuntu-latest
    needs:
      - build-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          image_tag: frontend-latest
          dockerfile: frontend/Dockerfile
          context: frontend
          github_token: ${{ secrets.GH_PAT }}

  build-backend-docker-image:
    name: Build backend Docker image
    runs-on: ubuntu-latest
    needs:
      - build-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          image_tag: backend-latest
          dockerfile: backend/Dockerfile
          context: backend
          github_token: ${{ secrets.GH_PAT }}

  build-single-docker-image:
    name: Build single Docker image
    runs-on: ubuntu-latest
    needs:
      - build-backend
      - build-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          image_tag: latest
          github_token: ${{ secrets.GH_PAT }}
